# REPO @ aaiwiki is using HTTPS.
- name: Install apt-transport-https to be able use aaiwiki repo
  apt: name=apt-transport-https state=latest

- name: Add our FreeRADIUS repository
  apt_repository:
    repo: deb https://aaiwiki.cesnet.cz/deb/jessie ./
    state: present
    update_cache: yes

- name: Update repo cache
  apt: update_cache=yes cache_valid_time=5  #86400

# It is needed to list all FreeRADIUS packages. Without that are
# updated only some of them.
- name: Install freeradius
  apt: name={{ item }} allow_unauthenticated=yes state=latest
  with_items:
    - freeradius
    - freeradius-ldap
    - freeradius-common
    - freeradius-config
    - freeradius-utils
    - pwgen

- name: create salt for CUI
  shell: pwgen 20 -n 1 > /etc/freeradius/cui_salt
  args:
    creates: /etc/freeradius/cui_salt

- name: read salt for CUI
  command: cat /etc/freeradius/cui_salt
  register: cui_salt
  changed_when: False
  check_mode: no

- set_fact: cui_salt={{ cui_salt.stdout }}

# copy needed files
- name: Copy freeRADIUS files 1/2
  copy: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=freerad group=freerad backup=yes
  with_items:
    - { src: freeradius.logrotate,
        dest: /etc/logrotate.d/freeradius }
    - { src: certs/chain_CESNET_CA3.pem,
        dest: /etc/freeradius/certs }
    - { src: certs/chain_TERENA_SSL_CA_3.pem,
        dest: /etc/freeradius/certs }
    - { src: post-proxy,
        dest: /etc/freeradius/mods-config/attr_filter/post-proxy }
    - { src: filter,
        dest: /etc/freeradius/policy.d/filter }
    - { src: eduroam-realm-checks,
        dest: /etc/freeradius/policy.d/eduroam-realm-checks }
  notify: restart freeradius

# it is posible that one of above certificate will never by used ...
- name: Copy freeRADIUS files 2/2
  copy: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=freerad group=freerad backup=yes
  with_items:
    - { src: "{{ eduroam.topRADIUS.CAChain }}",
        dest: /etc/freeradius/certs/topRADIUS_CAChain.pem }
  when: eduroam.topRADIUS.CAChain is defined 
  notify: restart freeradius

- name: Copy templated freeRADIUS files
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=root backup=yes
  with_items:
    - { src: default.j2,
        dest: /etc/freeradius/sites-available/default }
    - { src: tls.j2,
        dest: /etc/freeradius/sites-available/tls }
    - { src: inner-tunnel.j2,
        dest: /etc/freeradius/sites-available/inner-tunnel }
    - { src: clients.conf.j2,
        dest: /etc/freeradius/clients.conf }
    - { src: proxy.conf.j2,
        dest: /etc/freeradius/proxy.conf }
    - { src: radiusd.conf.j2,
        dest: /etc/freeradius/radiusd.conf }
    - { src: eap.j2,
        dest: /etc/freeradius/mods-available/eap }
    - { src: f_ticks.j2,
        dest: /etc/freeradius/mods-available/f_ticks }
    - { src: kill-weblogin.j2,
        dest: /etc/freeradius/policy.d/kill-weblogin }
    - { src: cui.j2,
        dest: /etc/freeradius/policy.d/cui }
  notify: restart freeradius

- name: Copy templated freeRADIUS files (IdP role)
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=root backup=yes
  when: eduroam.IdP
  with_items:
    - { src: ldap.j2,
        dest: /etc/freeradius/mods-available/ldap }
  notify: restart freeradius

- name: remove useless files (SP only mode)
  file: dest={{ item }} owner=root group=root state=absent
  when: eduroam.IdP == 0
  with_items:
    - /etc/freeradius/sites-enabled/inner-tunnel
    - /etc/freeradius/mods-enabled/eap
  notify: restart freeradius

- name: link needed files
  file: src={{ item.src }} dest={{ item.dest }} owner=root group=root state=link
  with_items:
    - { src: ../sites-available/tls,
        dest: /etc/freeradius/sites-enabled/tls }
    - { src: ../mods-available/f_ticks,
        dest: /etc/freeradius/mods-enabled/f_ticks }
    - { src: ../mods-available/cui,
        dest: /etc/freeradius/mods-enabled/cui }
  notify: restart freeradius

- name: link needed files (IdP role)
  file: src={{ item.src }} dest={{ item.dest }} owner=root group=root state=link
  when: eduroam.IdP
  with_items:
    - { src: ../sites-available/inner-tunnel,
        dest: /etc/freeradius/sites-enabled/inner-tunnel }
    - { src: ../mods-available/ldap,
        dest: /etc/freeradius/mods-enabled/ldap }
    - { src: ../mods-available/eap,
        dest: /etc/freeradius/mods-enabled/eap }
  notify: restart freeradius

# This is shitty, but we are using PKCS#12 instead of PEM because it
# is easier to protect file by password. And mainly because we are
# using similar ansible script to install Shibboleth IdP which is
# using PKCS#12 in native form.
- name: Copy PKCS#12 formated certificate & private key to server
  copy: src="{{ ansible_fqdn }}.pkcs12" dest=/etc/freeradius/certs/ mode=0400 owner=freerad group=freerad backup=yes
  register: certificate

- name: Extract private key from PKCS#12
  shell: 'openssl pkcs12 -in "{{ ansible_fqdn }}.pkcs12" -out "{{ ansible_fqdn }}.key" -nocerts -nodes -passin env:PKCS12_PSWD'
  environment:
    PKCS12_PSWD: "{{ certificate_password }}"
  args: 
    chdir: /etc/freeradius/certs/
  when: certificate.changed
  notify: restart freeradius

- name: Extract certificate from PKCS#12
  shell: 'openssl pkcs12 -in "{{ ansible_fqdn }}.pkcs12" -out "{{ ansible_fqdn }}.crt" -clcerts -nokeys -nodes -passin env:PKCS12_PSWD'
  environment:
    PKCS12_PSWD: "{{ certificate_password }}"
  args: 
    chdir: /etc/freeradius/certs/
  when: certificate.changed
  notify: restart freeradius

- name: Correct cert file permisions
  file: path={{ item }} owner=freerad group=freerad mode=0400 state=file
  with_items:
    - "/etc/freeradius/certs/{{ ansible_fqdn }}.crt"
    - "/etc/freeradius/certs/{{ ansible_fqdn }}.key"

- name: Copy detailed logs archivator
  copy: src=freeradius-monthly.sh dest=/usr/local/bin/freeradius-monthly.sh mode=0755 owner=root group=root backup=yes

- name: Install detailed logs archivator into cron
  cron: day=7 hour=7 minute=54 job=/usr/local/bin/freeradius-monthly.sh name="detailed log archivation"
