- name: install rad_eap_test from git
  get_url:
    url: https://raw.githubusercontent.com/CESNET/rad_eap_test/master/rad_eap_test
    dest: /usr/local/bin/rad_eap_test
    mode: 0755
    backup: yes

- name: install eapol_test on jessie
  get_url:
    url: https://aaiwiki.cesnet.cz/idp_files/eapol_test-2.6-jessie
    dest: /usr/local/bin/eapol_test
    mode: 0755
    checksum: "sha256:7aa9fa552aa7b29a8335fba7e249052637ac05dd8dc7089899a422919fed2186"
  when: ansible_distribution_release=='jessie'

- name: install eapol_test on stretch
  get_url:
    url: https://aaiwiki.cesnet.cz/idp_files/eapol_test-2.5-stretch
    dest: /usr/local/bin/eapol_test
    mode: 0755
    checksum: "sha256:7aa9fa552aa7b29a8335fba7e249052637ac05dd8dc7089899a422919fed2186"
  when: ansible_distribution_release=='stretch'
